import { supabase } from "../lib/supabase";

const selection = "*, projects(id, name, manager_id), repository_integrations(id, full_name, html_url), sprints(id, name), release_tasks(task_id, commit_url, pull_request_url, tasks(id, title, status, story_points)), release_checks(id, label, required, is_complete, completed_by, completed_at, profiles(id, full_name)), release_approvals(id, environment, status, approved_by, note, profiles(id, full_name)), deployments(id, environment, status, deployment_url, commit_sha, incident_url, started_at, finished_at, created_at, profiles(id, full_name))";
export async function getReleases() { const { data, error } = await supabase.from("releases").select(selection).order("target_date", { ascending: false }); if (error) throw error; return data || []; }
export async function createRelease(payload) { const { data, error } = await supabase.from("releases").insert(payload).select().single(); if (error) throw error; const checks = ["Release notes reviewed", "QA verification complete", "Security review complete", "Rollback plan confirmed"].map((label) => ({ release_id: data.id, label })); await supabase.from("release_checks").insert(checks); await supabase.from("release_approvals").insert(["development", "staging", "production"].map((environment) => ({ release_id: data.id, environment }))); return data; }
export async function updateRelease(id, payload) { const { error } = await supabase.from("releases").update(payload).eq("id", id); if (error) throw error; }
export async function addReleaseTask(releaseId, taskId, links = {}) { const { error } = await supabase.from("release_tasks").upsert({ release_id: releaseId, task_id: taskId, ...links }); if (error) throw error; }
export async function removeReleaseTask(releaseId, taskId) { const { error } = await supabase.from("release_tasks").delete().eq("release_id", releaseId).eq("task_id", taskId); if (error) throw error; }
export async function toggleReleaseCheck(check, userId) { const complete = !check.is_complete; const { error } = await supabase.from("release_checks").update({ is_complete: complete, completed_by: complete ? userId : null, completed_at: complete ? new Date().toISOString() : null }).eq("id", check.id); if (error) throw error; }
export async function updateApproval(id, status, userId, note = "") { const { error } = await supabase.from("release_approvals").update({ status, approved_by: userId, note, updated_at: new Date().toISOString() }).eq("id", id); if (error) throw error; }
export async function createDeployment(payload) { const { error } = await supabase.from("deployments").insert(payload); if (error) throw error; }
export async function updateDeployment(id, payload) { const { error } = await supabase.from("deployments").update(payload).eq("id", id); if (error) throw error; }
