import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CalendarDays, CheckCircle2, ExternalLink, GitCommit, PackageCheck, Plus, Rocket, ShieldCheck, Undo2 } from "lucide-react";
import { useAuth } from "../contexts/AuthContext";
import { supabase } from "../lib/supabase";
import { getProjects } from "../services/projectsService";
import { addReleaseTask, createDeployment, createRelease, getReleases, removeReleaseTask, toggleReleaseCheck, updateApproval, updateDeployment, updateRelease } from "../services/releasesService";

export default function Releases() {
  const { profile } = useAuth();
  const [releases, setReleases] = useState([]);
  const [projects, setProjects] = useState([]);
  const [repositories, setRepositories] = useState([]);
  const [sprints, setSprints] = useState([]);
  const [tasks, setTasks] = useState([]);
  const [activeId, setActiveId] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [draft, setDraft] = useState({ project_id: "", repository_id: "", sprint_id: "", version: "", name: "", release_notes: "", target_date: "", rollback_plan: "", status: "Draft" });
  const [taskDraft, setTaskDraft] = useState({ task_id: "", commit_url: "", pull_request_url: "" });
  const [deployment, setDeployment] = useState({ environment: "development", status: "Pending", deployment_url: "", commit_sha: "", incident_url: "" });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const role = String(profile?.role || "").trim().toLowerCase();
  const roleMode = role === "admin" || role === "administrator" ? "admin" : role === "manager" || role === "team manager" ? "manager" : "member";
  const canManage = roleMode !== "member";

  const load = async () => {
    try {
      setLoading(true);
      const [releaseData, projectData, repoResponse, sprintResponse, taskResponse] = await Promise.all([getReleases(), getProjects(), supabase.from("repository_integrations").select("id, full_name, project_id, html_url"), supabase.from("sprints").select("id, name, project_id, status"), supabase.from("tasks").select("id, title, status, project_id, sprint_id, story_points").order("created_at", { ascending: false })]);
      if (repoResponse.error) throw repoResponse.error; if (sprintResponse.error) throw sprintResponse.error; if (taskResponse.error) throw taskResponse.error;
      setReleases(releaseData); setProjects(projectData); setRepositories(repoResponse.data || []); setSprints(sprintResponse.data || []); setTasks(taskResponse.data || []);
      setActiveId((current) => current && releaseData.some((item) => item.id === current) ? current : releaseData[0]?.id || ""); setError("");
    } catch (requestError) { setError(requestError.message || "Release workspace could not be loaded."); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);
  const active = releases.find((release) => release.id === activeId);
  const includedIds = new Set(active?.release_tasks?.map((item) => item.task_id) || []);
  const eligibleTasks = tasks.filter((task) => active && task.project_id === active.project_id && !includedIds.has(task.id));
  const requiredChecks = active?.release_checks?.filter((check) => check.required) || [];
  const readiness = requiredChecks.length ? Math.round((requiredChecks.filter((check) => check.is_complete).length / requiredChecks.length) * 100) : 0;
  const productionApproved = active?.release_approvals?.some((approval) => approval.environment === "production" && approval.status === "Approved");
  const successDeployments = releases.flatMap((release) => release.deployments || []).filter((item) => item.status === "Succeeded").length;
  const failedDeployments = releases.flatMap((release) => release.deployments || []).filter((item) => item.status === "Failed").length;
  const deploymentSuccess = successDeployments + failedDeployments ? Math.round(successDeployments / (successDeployments + failedDeployments) * 100) : 0;
  const releasedThisMonth = releases.filter((release) => release.status === "Released" && release.released_at && new Date(release.released_at).getMonth() === new Date().getMonth()).length;
  const avgLeadDays = useMemo(() => { const completed = releases.filter((release) => release.released_at); return completed.length ? Math.round(completed.reduce((sum, release) => sum + (new Date(release.released_at) - new Date(release.created_at)) / 86400000, 0) / completed.length) : 0; }, [releases]);

  const create = async (event) => { event.preventDefault(); try { const payload = { ...draft, repository_id: draft.repository_id || null, sprint_id: draft.sprint_id || null, target_date: draft.target_date || null, created_by: profile.id }; await createRelease(payload); setShowCreate(false); setDraft({ project_id: "", repository_id: "", sprint_id: "", version: "", name: "", release_notes: "", target_date: "", rollback_plan: "", status: "Draft" }); await load(); } catch (requestError) { setError(requestError.message); } };
  const addTask = async (event) => { event.preventDefault(); if (!taskDraft.task_id) return; try { await addReleaseTask(active.id, taskDraft.task_id, { commit_url: taskDraft.commit_url || null, pull_request_url: taskDraft.pull_request_url || null }); setTaskDraft({ task_id: "", commit_url: "", pull_request_url: "" }); await load(); } catch (requestError) { setError(requestError.message); } };
  const toggleCheck = async (check) => { try { await toggleReleaseCheck(check, profile.id); await load(); } catch (requestError) { setError(requestError.message); } };
  const approve = async (approval, status) => { try { await updateApproval(approval.id, status, profile.id); await load(); } catch (requestError) { setError(requestError.message); } };
  const deploy = async (event) => { event.preventDefault(); try { await createDeployment({ release_id: active.id, ...deployment, deployed_by: profile.id, started_at: deployment.status === "In progress" ? new Date().toISOString() : null, finished_at: ["Succeeded", "Failed", "Rolled back"].includes(deployment.status) ? new Date().toISOString() : null }); if (deployment.environment === "production" && deployment.status === "Succeeded") await updateRelease(active.id, { status: "Released", released_at: new Date().toISOString() }); setDeployment({ environment: "development", status: "Pending", deployment_url: "", commit_sha: "", incident_url: "" }); await load(); } catch (requestError) { setError(requestError.message); } };

  if (loading) return <div className="p-5 text-slate-500">Loading releases…</div>;
  return <div className="space-y-4 pb-8">
    <header className="surface-panel p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-600">Software delivery</p><h1 className="mt-1 text-3xl font-bold">{roleMode === "admin" ? "Organization Releases" : roleMode === "manager" ? "Team Releases" : "My Release Work"}</h1><p className="mt-2 text-sm text-slate-500">{roleMode === "admin" ? "Monitor release health, approvals, frequency, and deployment outcomes." : roleMode === "manager" ? "Coordinate scope, readiness, approvals, deployment, and rollback plans." : "Review included work, submit readiness checks, and follow deployment progress."}</p></div>{canManage && <button onClick={() => setShowCreate(true)} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17} /> New release</button>}</div></header>
    {error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</p>}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Releases", releases.length, PackageCheck], ["This month", releasedThisMonth, CalendarDays], ["Deploy success", `${deploymentSuccess}%`, CheckCircle2], ["Avg lead time", `${avgLeadDays}d`, Rocket]].map(([label, value, Icon]) => <div key={label} className="surface-panel p-3"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-slate-500">{label}</p><Icon size={16} className="text-emerald-600" /></div><p className="mt-2 text-xl font-bold">{value}</p></div>)}</div>
    <div className="surface-panel flex flex-wrap items-center gap-3 p-3"><select value={activeId} onChange={(event) => setActiveId(event.target.value)} className="min-w-[280px] rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"><option value="">Select release</option>{releases.map((release) => <option key={release.id} value={release.id}>{release.version} · {release.name} · {release.status}</option>)}</select>{active && <><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold dark:bg-zinc-800">{active.projects?.name}</span><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-400">{active.status}</span>{canManage && <select value={active.status} onChange={async (event) => { await updateRelease(active.id, { status: event.target.value, released_at: event.target.value === "Released" ? new Date().toISOString() : active.released_at }); await load(); }} className="ml-auto rounded-lg border border-slate-200 bg-transparent px-2 py-1.5 text-xs dark:border-zinc-700">{["Draft", "Ready", "Deploying", "Released", "Failed", "Rolled back"].map((status) => <option key={status}>{status}</option>)}</select>}</>}</div>
    {!active ? <div className="surface-panel p-10 text-center"><Rocket className="mx-auto text-slate-300" size={44} /><h2 className="mt-3 font-bold">No accessible releases</h2></div> : <>
      <section className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-4"><div className="surface-panel p-4"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">{active.version} · {active.name}</h2><p className="mt-1 text-xs text-slate-500">Target {active.target_date || "not scheduled"} · {active.repository_integrations?.full_name || "No repository"} · {active.sprints?.name || "No sprint"}</p></div><span className="text-lg font-bold text-emerald-600">{readiness}% ready</span></div><div className="mt-3 h-2 rounded-full bg-slate-200 dark:bg-zinc-800"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${readiness}%` }} /></div><h3 className="mt-4 text-sm font-bold">Release notes</h3><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-600 dark:text-zinc-300">{active.release_notes || "No release notes provided."}</p><h3 className="mt-4 flex items-center gap-2 text-sm font-bold"><Undo2 size={15} /> Rollback plan</h3><p className="mt-1 text-sm text-slate-600 dark:text-zinc-300">{active.rollback_plan || "No rollback plan documented."}</p></div>
        <div className="surface-panel p-4"><div className="flex items-center justify-between"><h2 className="font-bold">Included work</h2><span className="text-xs text-slate-500">{active.release_tasks?.length || 0} tasks</span></div>{canManage && <form onSubmit={addTask} className="mt-3 grid gap-2"><select value={taskDraft.task_id} onChange={(event) => setTaskDraft({ ...taskDraft, task_id: event.target.value })} className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"><option value="">Select project task</option>{eligibleTasks.map((task) => <option key={task.id} value={task.id}>{task.title} · {task.status}</option>)}</select><div className="grid grid-cols-2 gap-2"><input type="url" value={taskDraft.commit_url} onChange={(event) => setTaskDraft({ ...taskDraft, commit_url: event.target.value })} placeholder="Commit URL" className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-xs dark:border-zinc-700" /><input type="url" value={taskDraft.pull_request_url} onChange={(event) => setTaskDraft({ ...taskDraft, pull_request_url: event.target.value })} placeholder="Pull request URL" className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-xs dark:border-zinc-700" /></div><button className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Add task</button></form>}<div className="mt-3 space-y-2">{active.release_tasks?.map((item) => <div key={item.task_id} className="rounded-xl border border-slate-200 p-3 dark:border-zinc-800"><div className="flex items-center justify-between gap-2"><p className="text-sm font-bold">{item.tasks?.title}</p>{canManage && <button onClick={async () => { await removeReleaseTask(active.id, item.task_id); await load(); }} className="text-xs text-red-600">Remove</button>}</div><p className="mt-1 text-xs text-slate-500">{item.tasks?.status} · {item.tasks?.story_points || 0} points</p><div className="mt-2 flex gap-3">{item.commit_url && <a href={item.commit_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-bold text-emerald-600"><GitCommit size={13} /> Commit</a>}{item.pull_request_url && <a href={item.pull_request_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-bold text-emerald-600">PR <ExternalLink size={12} /></a>}</div></div>)}</div></div></div>
      <div className="space-y-4"><div className="surface-panel p-4"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-emerald-600" /><h2 className="font-bold">Readiness checklist</h2></div><div className="mt-3 space-y-2">{active.release_checks?.map((check) => <button key={check.id} onClick={() => toggleCheck(check)} className="flex w-full items-center gap-3 rounded-xl border border-slate-200 p-3 text-left dark:border-zinc-800"><span className={`flex h-5 w-5 items-center justify-center rounded-full border ${check.is_complete ? "border-emerald-500 bg-emerald-500 text-white" : "border-slate-300"}`}>{check.is_complete && <CheckCircle2 size={13} />}</span><span className="flex-1 text-sm font-semibold">{check.label}</span>{check.profiles?.full_name && <span className="text-xs text-slate-400">{check.profiles.full_name}</span>}</button>)}</div></div>
        <div className="surface-panel p-4"><h2 className="font-bold">Approval gates</h2><div className="mt-3 space-y-2">{active.release_approvals?.map((approval) => <div key={approval.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-zinc-800"><span className="flex-1 text-sm font-semibold capitalize">{approval.environment}</span><span className={`text-xs font-bold ${approval.status === "Approved" ? "text-emerald-600" : approval.status === "Rejected" ? "text-red-600" : "text-amber-600"}`}>{approval.status}</span>{canManage && <><button onClick={() => approve(approval, "Approved")} className="text-xs font-bold text-emerald-600">Approve</button><button onClick={() => approve(approval, "Rejected")} className="text-xs font-bold text-red-600">Reject</button></>}</div>)}</div></div>
        <div className="surface-panel p-4"><h2 className="font-bold">Deployment history</h2>{canManage && <form onSubmit={deploy} className="mt-3 grid gap-2 sm:grid-cols-2"><select value={deployment.environment} onChange={(event) => setDeployment({ ...deployment, environment: event.target.value })} className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"><option value="development">Development</option><option value="staging">Staging</option><option value="production" disabled={!productionApproved || readiness < 100}>Production</option></select><select value={deployment.status} onChange={(event) => setDeployment({ ...deployment, status: event.target.value })} className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700">{["Pending", "In progress", "Succeeded", "Failed", "Rolled back"].map((status) => <option key={status}>{status}</option>)}</select><input value={deployment.commit_sha} onChange={(event) => setDeployment({ ...deployment, commit_sha: event.target.value })} placeholder="Commit SHA" className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700" /><input type="url" value={deployment.deployment_url} onChange={(event) => setDeployment({ ...deployment, deployment_url: event.target.value })} placeholder="Deployment URL" className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700" /><input type="url" value={deployment.incident_url} onChange={(event) => setDeployment({ ...deployment, incident_url: event.target.value })} placeholder="Incident URL if failed" className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700 sm:col-span-2" /><button disabled={deployment.environment === "production" && (!productionApproved || readiness < 100)} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-40 sm:col-span-2">Record deployment</button></form>}<div className="mt-3 space-y-2">{active.deployments?.map((item) => <div key={item.id} className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-zinc-950"><div className="flex items-center justify-between"><p className="font-bold capitalize">{item.environment}</p><span className={item.status === "Succeeded" ? "text-emerald-600" : item.status === "Failed" ? "text-red-600" : "text-amber-600"}>{item.status}</span></div><p className="mt-1 text-xs text-slate-500">{item.commit_sha || "No commit"} · {new Date(item.created_at).toLocaleString()}</p>{item.deployment_url && <a href={item.deployment_url} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 text-xs font-bold text-emerald-600">Open deployment <ExternalLink size={12} /></a>}{item.incident_url && <a href={item.incident_url} target="_blank" rel="noreferrer" className="ml-3 text-xs font-bold text-red-600">Incident</a>}</div>)}</div></div></div></section>
    </>}
    {showCreate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={create} className="max-h-[90vh] w-full max-w-xl space-y-3 overflow-y-auto rounded-2xl bg-white p-5 dark:bg-zinc-900"><h2 className="text-xl font-bold">Create release</h2><div className="grid grid-cols-2 gap-2"><input required value={draft.version} onChange={(event) => setDraft({ ...draft, version: event.target.value })} placeholder="Version, e.g. v1.2.0" className="input-field" /><input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="Release name" className="input-field" /></div><select required value={draft.project_id} onChange={(event) => setDraft({ ...draft, project_id: event.target.value, repository_id: "", sprint_id: "" })} className="input-field"><option value="">Select project</option>{projects.filter((project) => roleMode === "admin" || project.manager_id === profile.id).map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><select value={draft.repository_id} onChange={(event) => setDraft({ ...draft, repository_id: event.target.value })} className="input-field"><option value="">Repository</option>{repositories.filter((repo) => !repo.project_id || repo.project_id === draft.project_id).map((repo) => <option key={repo.id} value={repo.id}>{repo.full_name}</option>)}</select><select value={draft.sprint_id} onChange={(event) => setDraft({ ...draft, sprint_id: event.target.value })} className="input-field"><option value="">Sprint</option>{sprints.filter((sprint) => sprint.project_id === draft.project_id).map((sprint) => <option key={sprint.id} value={sprint.id}>{sprint.name}</option>)}</select></div><input type="date" value={draft.target_date} onChange={(event) => setDraft({ ...draft, target_date: event.target.value })} className="input-field" /><textarea value={draft.release_notes} onChange={(event) => setDraft({ ...draft, release_notes: event.target.value })} placeholder="Release notes" className="input-field" /><textarea value={draft.rollback_plan} onChange={(event) => setDraft({ ...draft, rollback_plan: event.target.value })} placeholder="Rollback plan" className="input-field" /><div className="flex justify-end gap-2"><button type="button" onClick={() => setShowCreate(false)} className="rounded-xl px-4 py-2">Cancel</button><button className="rounded-xl bg-emerald-600 px-4 py-2 font-semibold text-white">Create release</button></div></form></div>}
  </div>;
}
