import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CalendarDays, CheckCircle2, Clock3, Gauge, GripVertical, Plus, Target, Users } from "lucide-react";
import { useAuth } from "../contexts/AuthContext";
import { supabase } from "../lib/supabase";
import { getProjects } from "../services/projectsService";
import { assignTaskToSprint, createSprint, getSprints, saveSprintMember, saveStandup, updateSprint, updateTaskEstimate } from "../services/sprintsService";

export default function Sprints() {
  const { profile } = useAuth();
  const [sprints, setSprints] = useState([]);
  const [tasks, setTasks] = useState([]);
  const [projects, setProjects] = useState([]);
  const [activeId, setActiveId] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [carryTarget, setCarryTarget] = useState("");
  const [draft, setDraft] = useState({ name: "", goal: "", project_id: "", start_date: "", end_date: "", status: "Planning" });
  const [standup, setStandup] = useState({ completed: "", planned: "", blockers: "" });
  const role = String(profile?.role || "").trim().toLowerCase();
  const roleMode = role === "admin" || role === "administrator" ? "admin" : role === "manager" || role === "team manager" ? "manager" : "member";
  const canPlan = roleMode !== "member";

  const load = async () => {
    try {
      setLoading(true);
      const [sprintData, projectData, taskResponse] = await Promise.all([getSprints(), getProjects(), supabase.from("tasks").select("id, title, status, priority, progress, project_id, sprint_id, story_points, estimated_hours, blocked_reason, assignee_id, projects(id, name), task_assignees(user_id, profiles(id, full_name))").order("created_at", { ascending: false })]);
      if (taskResponse.error) throw taskResponse.error;
      setSprints(sprintData); setProjects(projectData); setTasks(taskResponse.data || []);
      setActiveId((current) => current && sprintData.some((sprint) => sprint.id === current) ? current : sprintData.find((sprint) => sprint.status === "Active")?.id || sprintData[0]?.id || "");
      setError("");
    } catch (requestError) { setError(requestError.message || "Sprint workspace could not be loaded."); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);

  const active = sprints.find((sprint) => sprint.id === activeId);
  const sprintTasks = tasks.filter((task) => task.sprint_id === activeId);
  const backlog = tasks.filter((task) => !task.sprint_id && (!active || task.project_id === active.project_id));
  const completed = sprintTasks.filter((task) => String(task.status).toLowerCase() === "completed");
  const totalPoints = sprintTasks.reduce((sum, task) => sum + Number(task.story_points || 0), 0);
  const completedPoints = completed.reduce((sum, task) => sum + Number(task.story_points || 0), 0);
  const blocked = sprintTasks.filter((task) => task.blocked_reason);
  const sprintProgress = totalPoints ? Math.round((completedPoints / totalPoints) * 100) : 0;

  const members = useMemo(() => {
    if (!active) return [];
    const project = projects.find((item) => item.id === active.project_id);
    const people = [project?.manager, ...(project?.project_members || []).map((member) => member.profiles || member), ...sprintTasks.flatMap((task) => (task.task_assignees || []).map((assignment) => assignment.profiles || assignment))].filter(Boolean);
    return [...new Map(people.map((person) => [person.id, person])).values()];
  }, [active, projects, sprintTasks]);

  const create = async (event) => {
    event.preventDefault();
    try { await createSprint({ ...draft, created_by: profile.id }); setShowCreate(false); setDraft({ name: "", goal: "", project_id: "", start_date: "", end_date: "", status: "Planning" }); await load(); }
    catch (requestError) { setError(requestError.message); }
  };
  const moveTask = async (taskId, sprintId) => { try { await assignTaskToSprint(taskId, sprintId); await load(); } catch (requestError) { setError(requestError.message); } };
  const drop = (event, sprintId) => { event.preventDefault(); const taskId = event.dataTransfer.getData("task-id"); if (taskId && canPlan) moveTask(taskId, sprintId); };
  const saveCheckIn = async (event) => { event.preventDefault(); try { await saveStandup(active.id, profile.id, standup); setStandup({ completed: "", planned: "", blockers: "" }); await load(); } catch (requestError) { setError(requestError.message); } };
  const setCapacity = async (userId, value) => { try { await saveSprintMember(active.id, userId, value); await load(); } catch (requestError) { setError(requestError.message); } };
  const finishSprint = async () => { if (!window.confirm("Complete this sprint? Unfinished tasks will remain attached for review or carry-over.")) return; try { await updateSprint(active.id, { status: "Completed", completed_at: new Date().toISOString() }); await load(); } catch (requestError) { setError(requestError.message); } };
  const carryOver = async () => { if (!carryTarget) return; try { await Promise.all(sprintTasks.filter((task) => String(task.status).toLowerCase() !== "completed").map((task) => assignTaskToSprint(task.id, carryTarget))); setCarryTarget(""); await load(); } catch (requestError) { setError(requestError.message); } };

  if (loading) return <div className="p-5 text-slate-500">Loading sprint workspace…</div>;
  return <div className="space-y-4 pb-8">
    <header className="surface-panel p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-600">Delivery planning</p><h1 className="mt-1 text-3xl font-bold">{roleMode === "admin" ? "Organization Sprints" : roleMode === "manager" ? "Team Sprints" : "My Sprint"}</h1><p className="mt-2 text-sm text-slate-500">{roleMode === "admin" ? "Monitor capacity, sprint health, and delivery across accessible projects." : roleMode === "manager" ? "Plan the backlog, capacity, blockers, and team commitments." : "Track your sprint commitments, priorities, blockers, and daily check-ins."}</p></div>{canPlan && <button onClick={() => setShowCreate(true)} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17} /> New sprint</button>}</div></header>
    {error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</p>}
    <div className="surface-panel flex flex-wrap items-center gap-3 p-3"><select value={activeId} onChange={(event) => setActiveId(event.target.value)} className="min-w-[240px] rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700"><option value="">Select a sprint</option>{sprints.map((sprint) => <option key={sprint.id} value={sprint.id}>{sprint.name} · {sprint.status}</option>)}</select>{active && <><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold dark:bg-zinc-800">{active.projects?.name}</span><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-400">{active.status}</span>{canPlan && active.status !== "Completed" && <button onClick={finishSprint} className="ml-auto text-xs font-bold text-emerald-600">Complete sprint</button>}{canPlan && active.status === "Completed" && <div className="ml-auto flex items-center gap-2"><select value={carryTarget} onChange={(event) => setCarryTarget(event.target.value)} className="rounded-lg border border-slate-200 bg-transparent px-2 py-1.5 text-xs dark:border-zinc-700"><option value="">Carry unfinished to…</option>{sprints.filter((sprint) => sprint.project_id === active.project_id && sprint.id !== active.id && sprint.status !== "Completed").map((sprint) => <option key={sprint.id} value={sprint.id}>{sprint.name}</option>)}</select><button onClick={carryOver} disabled={!carryTarget} className="text-xs font-bold text-emerald-600 disabled:opacity-40">Carry over</button></div>}</>}</div>
    {!active ? <div className="surface-panel p-10 text-center"><Target className="mx-auto text-slate-300" size={44} /><h2 className="mt-3 font-bold">No accessible sprints yet</h2><p className="mt-1 text-sm text-slate-500">A manager or admin can create the first sprint.</p></div> : <>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Progress", `${sprintProgress}%`, Gauge], ["Velocity", `${completedPoints}/${totalPoints} pts`, CheckCircle2], ["Tasks", sprintTasks.length, Target], ["Blocked", blocked.length, AlertTriangle], ["Dates", `${active.start_date} → ${active.end_date}`, CalendarDays]].map(([label, value, Icon]) => <div key={label} className="surface-panel p-3"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-slate-500">{label}</p><Icon size={16} className="text-emerald-600" /></div><p className="mt-2 truncate text-lg font-bold">{value}</p></div>)}</div>
      <section className="grid gap-4 xl:grid-cols-[1fr_1.3fr]">
        <div onDragOver={(event) => event.preventDefault()} onDrop={(event) => drop(event, null)} className="surface-panel min-h-[300px] p-4"><div className="flex items-center justify-between"><div><h2 className="font-bold">Backlog</h2><p className="text-xs text-slate-500">{backlog.length} project tasks</p></div></div><div className="mt-3 space-y-2">{backlog.map((task) => <TaskCard key={task.id} task={task} canPlan={canPlan} onMove={() => moveTask(task.id, active.id)} onEstimate={updateTaskEstimate} reload={load} />)}{!backlog.length && <p className="rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500 dark:border-zinc-700">Backlog is clear.</p>}</div></div>
        <div onDragOver={(event) => event.preventDefault()} onDrop={(event) => drop(event, active.id)} className="surface-panel min-h-[300px] p-4"><div><h2 className="font-bold">Sprint commitment</h2><p className="text-xs text-slate-500">{active.goal || "No sprint goal provided"}</p></div><div className="mt-3 space-y-2">{sprintTasks.map((task) => <TaskCard key={task.id} task={task} canPlan={canPlan} onMove={() => moveTask(task.id, null)} onEstimate={updateTaskEstimate} reload={load} inSprint />)}{!sprintTasks.length && <p className="rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500 dark:border-zinc-700">Drag backlog tasks here to plan the sprint.</p>}</div></div>
      </section>
      <section className="grid gap-4 xl:grid-cols-2"><div className="surface-panel p-4"><div className="flex items-center gap-2"><Users size={18} className="text-emerald-600" /><h2 className="font-bold">Capacity and workload</h2></div><div className="mt-3 space-y-2">{members.map((member) => { const capacity = active.sprint_members?.find((item) => item.user_id === member.id)?.capacity_hours || 40; const assigned = sprintTasks.filter((task) => task.assignee_id === member.id || task.task_assignees?.some((item) => item.user_id === member.id)).reduce((sum, task) => sum + Number(task.estimated_hours || 0), 0); const loadPercent = capacity ? Math.round((assigned / capacity) * 100) : 0; return <div key={member.id} className="rounded-xl border border-slate-200 p-3 dark:border-zinc-800"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold">{member.full_name}</p><p className={`text-xs ${loadPercent > 100 ? "text-red-600" : "text-slate-500"}`}>{assigned}h assigned · {loadPercent}% load</p></div>{canPlan ? <input type="number" min="0" defaultValue={capacity} onBlur={(event) => setCapacity(member.id, event.target.value)} className="w-20 rounded-lg border border-slate-200 bg-transparent px-2 py-1 text-sm dark:border-zinc-700" /> : <span className="text-xs text-slate-500">{capacity}h capacity</span>}</div><div className="mt-2 h-1.5 rounded-full bg-slate-200 dark:bg-zinc-800"><div className={`h-full rounded-full ${loadPercent > 100 ? "bg-red-500" : "bg-emerald-500"}`} style={{ width: `${Math.min(100, loadPercent)}%` }} /></div></div>; })}</div></div>
        <div className="surface-panel p-4"><div className="flex items-center gap-2"><Clock3 size={18} className="text-emerald-600" /><h2 className="font-bold">Daily stand-up</h2></div><form onSubmit={saveCheckIn} className="mt-3 space-y-2"><textarea value={standup.completed} onChange={(event) => setStandup({ ...standup, completed: event.target.value })} placeholder="What did you complete?" className="w-full rounded-xl border border-slate-200 bg-transparent p-3 text-sm dark:border-zinc-700" /><textarea value={standup.planned} onChange={(event) => setStandup({ ...standup, planned: event.target.value })} placeholder="What will you work on next?" className="w-full rounded-xl border border-slate-200 bg-transparent p-3 text-sm dark:border-zinc-700" /><textarea value={standup.blockers} onChange={(event) => setStandup({ ...standup, blockers: event.target.value })} placeholder="Any blockers?" className="w-full rounded-xl border border-slate-200 bg-transparent p-3 text-sm dark:border-zinc-700" /><button className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Save today's check-in</button></form><div className="mt-4 max-h-52 space-y-2 overflow-y-auto">{active.sprint_standups?.slice().sort((a,b) => new Date(b.standup_date)-new Date(a.standup_date)).map((item) => <div key={item.id} className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-zinc-950"><p className="font-bold">{item.profiles?.full_name || "Team member"} · {item.standup_date}</p>{item.completed && <p className="mt-1 text-slate-600 dark:text-zinc-300">Done: {item.completed}</p>}{item.planned && <p className="text-slate-600 dark:text-zinc-300">Next: {item.planned}</p>}{item.blockers && <p className="text-red-600">Blocked: {item.blockers}</p>}</div>)}</div></div></section>
    </>}
    {showCreate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={create} className="w-full max-w-lg space-y-3 rounded-2xl bg-white p-5 dark:bg-zinc-900"><h2 className="text-xl font-bold">Create sprint</h2><input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="Sprint name" className="input-field" /><textarea value={draft.goal} onChange={(event) => setDraft({ ...draft, goal: event.target.value })} placeholder="Sprint goal" className="input-field" /><select required value={draft.project_id} onChange={(event) => setDraft({ ...draft, project_id: event.target.value })} className="input-field"><option value="">Select managed project</option>{projects.filter((project) => roleMode === "admin" || project.manager_id === profile.id).map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><input required type="date" value={draft.start_date} onChange={(event) => setDraft({ ...draft, start_date: event.target.value })} className="input-field" /><input required type="date" value={draft.end_date} onChange={(event) => setDraft({ ...draft, end_date: event.target.value })} className="input-field" /></div><div className="flex justify-end gap-2"><button type="button" onClick={() => setShowCreate(false)} className="rounded-xl px-4 py-2">Cancel</button><button className="rounded-xl bg-emerald-600 px-4 py-2 font-semibold text-white">Create</button></div></form></div>}
  </div>;
}

function TaskCard({ task, canPlan, onMove, onEstimate, reload, inSprint = false }) {
  return <article draggable={canPlan} onDragStart={(event) => event.dataTransfer.setData("task-id", task.id)} className="rounded-xl border border-slate-200 bg-white p-3 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex items-start gap-2">{canPlan && <GripVertical size={16} className="mt-0.5 shrink-0 cursor-grab text-slate-400" />}<div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-bold">{task.title}</p><span className="text-xs font-semibold text-slate-500">{task.story_points || 0} pts</span></div><p className="mt-1 text-xs text-slate-500">{task.status} · {task.estimated_hours || 0}h{task.blocked_reason ? <span className="text-red-600"> · Blocked</span> : ""}</p>{canPlan && <div className="mt-2 flex items-center gap-2"><input aria-label="Story points" type="number" min="0" defaultValue={task.story_points || 0} onBlur={async (event) => { await onEstimate(task.id, event.target.value, task.estimated_hours || ""); await reload(); }} className="w-16 rounded-lg border border-slate-200 bg-transparent px-2 py-1 text-xs dark:border-zinc-700" /><input aria-label="Estimated hours" type="number" min="0" defaultValue={task.estimated_hours || ""} onBlur={async (event) => { await onEstimate(task.id, task.story_points || 0, event.target.value); await reload(); }} className="w-16 rounded-lg border border-slate-200 bg-transparent px-2 py-1 text-xs dark:border-zinc-700" /><button onClick={onMove} className="ml-auto text-xs font-bold text-emerald-600">{inSprint ? "Backlog" : "Add"}</button></div>}</div></div></article>;
}
