import {
  Download,
} from "lucide-react";

function ReportsTable({
  reports,
  handleDownload,
}) {
  return (
    <div className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-3xl overflow-hidden">

      <div className="overflow-x-auto">

        <table className="w-full">

          <thead className="bg-slate-50 dark:bg-zinc-800">

            <tr>

              <th className="text-left p-5 dark:text-white">
                Report
              </th>

              <th className="text-left p-5 dark:text-white">
                Category
              </th>

              <th className="text-left p-5 dark:text-white">
                Project
              </th>

              <th className="text-left p-5 dark:text-white">
                Generated By
              </th>

              <th className="text-left p-5 dark:text-white">
                Date
              </th>

              <th className="text-left p-5 dark:text-white">
                Status
              </th>

              <th className="text-left p-5 dark:text-white">
                Type
              </th>

              <th className="text-left p-5 dark:text-white">
                Action
              </th>

            </tr>

          </thead>

          <tbody>

            {reports.map((report) => (

              <tr
                key={report.id}
                className="border-t border-slate-200 dark:border-zinc-800"
              >

                <td className="p-5 font-semibold dark:text-white">
                  {report.title}
                </td>

                <td className="p-5 text-slate-500 dark:text-zinc-400">
                  {report.category}
                </td>

                <td className="p-5 dark:text-white">
                  {report.project}
                </td>

                <td className="p-5 dark:text-white">
                  {report.generatedBy}
                </td>

                <td className="p-5 dark:text-white">
                  {report.date}
                </td>

                <td className="p-5">

                  <span
                    className={`px-3 py-1 rounded-full text-xs font-semibold
                      ${
                        report.status === "Completed"
                          ? "bg-emerald-100 text-emerald-700"
                          : "bg-amber-100 text-amber-700"
                      }
                    `}
                  >
                    {report.status}
                  </span>

                </td>

                <td className="p-5 dark:text-white">
                  {report.type}
                </td>

                <td className="p-5">

                  <button
            onClick={() =>
                handleDownload(report)
            }
            className="flex items-center gap-2 text-emerald-600 hover:text-emerald-700 font-semibold"
            >

            <Download size={18} />

            Download

            </button>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>

    </div>
  );
}

export default ReportsTable;