import {
  Download,
} from "lucide-react";

function ReportCard({ report }) {
  return (
    <div className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-3xl p-6">

      <div className="flex items-start justify-between gap-4">

        <div>

          <h2 className="text-xl font-bold dark:text-white">
            {report.title}
          </h2>

          <p className="text-slate-500 dark:text-zinc-400 mt-2">
            {report.project}
          </p>

        </div>

        <span
          className={`px-3 py-1 rounded-full text-xs font-semibold
            ${
              report.status === "Completed"
                ? "bg-emerald-100 text-emerald-700"
                : "bg-amber-100 text-amber-700"
            }
          `}
        >
          {report.status}
        </span>

      </div>

      <div className="grid grid-cols-2 gap-4 mt-8">

        <div>

          <p className="text-slate-500 dark:text-zinc-400 text-sm">
            Category
          </p>

          <h3 className="font-semibold mt-2 dark:text-white">
            {report.category}
          </h3>

        </div>

        <div>

          <p className="text-slate-500 dark:text-zinc-400 text-sm">
            Type
          </p>

          <h3 className="font-semibold mt-2 dark:text-white">
            {report.type}
          </h3>

        </div>

        <div>

          <p className="text-slate-500 dark:text-zinc-400 text-sm">
            Generated By
          </p>

          <h3 className="font-semibold mt-2 dark:text-white">
            {report.generatedBy}
          </h3>

        </div>

        <div>

          <p className="text-slate-500 dark:text-zinc-400 text-sm">
            Date
          </p>

          <h3 className="font-semibold mt-2 dark:text-white">
            {report.date}
          </h3>

        </div>

      </div>

      <div className="flex items-center gap-3 mt-8">

        <button className="flex-1 bg-emerald-600 hover:bg-emerald-700 text-white py-3 rounded-xl transition">

          View Report

        </button>

        <button className="flex items-center justify-center gap-2 border border-slate-200 dark:border-zinc-800 px-5 py-3 rounded-xl dark:text-white hover:bg-slate-100 dark:hover:bg-zinc-800 transition">

          <Download size={18} />

        </button>

      </div>

    </div>
  );
}

export default ReportCard;