import {
  Download,
  Eye,
  FileText,
  CalendarDays,
  User2,
  FolderKanban,
} from "lucide-react";

function ReportsTable({
  reports,
  handleDownload,
  handleViewReport,
}) {
  const getStatusStyles = (status) => {
    switch (status) {
      case "Completed":
        return "bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-400";

      case "Pending":
        return "bg-amber-100 text-amber-700 dark:bg-amber-950/40 dark:text-amber-400";

      default:
        return "bg-slate-100 text-slate-700 dark:bg-zinc-800 dark:text-zinc-300";
    }
  };

  return (
    <div className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-[28px] overflow-hidden shadow-sm">

      <div className="overflow-x-auto">

        <table className="w-full min-w-[1100px]">

          <thead className="bg-slate-50 dark:bg-zinc-800/80">

            <tr>

              <th className="text-left px-6 py-5 text-sm font-semibold text-slate-600 dark:text-zinc-300">
                Report
              </th>

              <th className="text-left px-6 py-5 text-sm font-semibold text-slate-600 dark:text-zinc-300">
                Category
              </th>

              <th className="text-left px-6 py-5 text-sm font-semibold text-slate-600 dark:text-zinc-300">
                Project
              </th>

              <th className="text-left px-6 py-5 text-sm font-semibold text-slate-600 dark:text-zinc-300">
                Generated By
              </th>

              <th className="text-left px-6 py-5 text-sm font-semibold text-slate-600 dark:text-zinc-300">
                Date
              </th>

              <th className="text-left px-6 py-5 text-sm font-semibold text-slate-600 dark:text-zinc-300">
                Status
              </th>

              <th className="text-left px-6 py-5 text-sm font-semibold text-slate-600 dark:text-zinc-300">
                Type
              </th>

              <th className="text-center px-6 py-5 text-sm font-semibold text-slate-600 dark:text-zinc-300">
                Actions
              </th>

            </tr>

          </thead>

          <tbody>

            {reports.map((report) => (

              <tr
                key={report.id}
                className="border-t border-slate-200 dark:border-zinc-800 hover:bg-slate-50 dark:hover:bg-zinc-800/40 transition"
              >

                <td className="px-6 py-5">

                  <div className="flex items-center gap-4">

                    <div className="w-12 h-12 rounded-2xl bg-emerald-100 dark:bg-emerald-950/40 flex items-center justify-center shrink-0">

                      <FileText
                        size={20}
                        className="text-emerald-600 dark:text-emerald-400"
                      />

                    </div>

                    <div>

                      <h3 className="font-semibold dark:text-white">
                        {report.title}
                      </h3>

                      <p className="text-sm text-slate-500 dark:text-zinc-400 mt-1">
                        {report.type} Report
                      </p>

                    </div>

                  </div>

                </td>

                <td className="px-6 py-5">

                  <div className="flex items-center gap-2">

                    <FolderKanban
                      size={16}
                      className="text-emerald-600"
                    />

                    <span className="font-medium text-slate-600 dark:text-zinc-300">
                      {report.category}
                    </span>

                  </div>

                </td>

                <td className="px-6 py-5 dark:text-white">
                  {report.project}
                </td>

                <td className="px-6 py-5">

                  <div className="flex items-center gap-2">

                    <User2
                      size={16}
                      className="text-slate-400"
                    />

                    <span className="dark:text-white">
                      {report.generatedBy}
                    </span>

                  </div>

                </td>

                <td className="px-6 py-5">

                  <div className="flex items-center gap-2 text-slate-600 dark:text-zinc-300">

                    <CalendarDays size={16} />

                    <span>{report.date}</span>

                  </div>

                </td>

                <td className="px-6 py-5">

                  <span
                    className={`px-4 py-1.5 rounded-full text-xs font-semibold whitespace-nowrap ${getStatusStyles(
                      report.status
                    )}`}
                  >
                    {report.status}
                  </span>

                </td>

                <td className="px-6 py-5">

                  <span className="px-3 py-1 rounded-xl bg-slate-100 dark:bg-zinc-800 text-sm font-semibold dark:text-white">

                    {report.type}

                  </span>

                </td>

                <td className="px-6 py-5">

                  <div className="flex items-center justify-center gap-3">

                    <button
                      onClick={() =>
                        handleViewReport(report)
                      }
                      className="flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white transition font-medium"
                    >

                      <Eye size={16} />

                      View

                    </button>

                    <button
                      onClick={() =>
                        handleDownload(report)
                      }
                      className="w-11 h-11 rounded-xl border border-slate-200 dark:border-zinc-700 dark:text-white hover:bg-slate-100 dark:hover:bg-zinc-800 flex items-center justify-center transition"
                    >

                      <Download size={18} />

                    </button>

                  </div>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>

      {reports.length === 0 && (

        <div className="p-5 text-center">

          <div className="w-20 h-20 rounded-full bg-slate-100 dark:bg-zinc-800 flex items-center justify-center mx-auto">

            <FileText
              size={36}
              className="text-slate-400"
            />

          </div>

          <h2 className="text-2xl font-bold mt-6 dark:text-white">
            No Reports Found
          </h2>

          <p className="text-slate-500 dark:text-zinc-400 mt-3">
            No reports match your current filters.
          </p>

        </div>

      )}

    </div>
  );
}

export default ReportsTable;
