import {
  Download,
  Eye,
  CalendarDays,
  FileText,
  User2,
  FolderKanban,
  BarChart3,
} from "lucide-react";

function ReportCard({
  report,
  handleDownload,
  handleViewReport,
}) {
  const getStatusStyles = () => {
    switch (report.status) {
      case "Completed":
        return "bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-400";

      case "Pending":
        return "bg-amber-100 text-amber-700 dark:bg-amber-950/40 dark:text-amber-400";

      default:
        return "bg-slate-100 text-slate-700 dark:bg-zinc-800 dark:text-zinc-300";
    }
  };

  return (
    <div className="group bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-[28px] p-5 hover:shadow-2xl hover:shadow-emerald-500/10 transition-all duration-300 hover:-translate-y-1">

      <div className="flex items-start justify-between gap-4">

        <div className="flex items-start gap-4">

          <div className="w-14 h-14 rounded-2xl bg-emerald-100 dark:bg-emerald-950/40 flex items-center justify-center shrink-0">

            <BarChart3
              size={26}
              className="text-emerald-600 dark:text-emerald-400"
            />

          </div>

          <div>

            <h2 className="text-xl font-bold dark:text-white leading-tight">
              {report.title}
            </h2>

            <p className="text-slate-500 dark:text-zinc-400 mt-2">
              {report.project}
            </p>

          </div>

        </div>

        <span
          className={`px-4 py-1.5 rounded-full text-xs font-semibold whitespace-nowrap ${getStatusStyles()}`}
        >
          {report.status}
        </span>

      </div>

      <div className="grid grid-cols-2 gap-5 mt-8">

        <div className="bg-slate-50 dark:bg-zinc-800/70 rounded-2xl p-4">

          <div className="flex items-center gap-2 text-slate-500 dark:text-zinc-400">

            <FolderKanban size={16} />

            <p className="text-sm">
              Category
            </p>

          </div>

          <h3 className="font-semibold mt-3 dark:text-white">
            {report.category}
          </h3>

        </div>

        <div className="bg-slate-50 dark:bg-zinc-800/70 rounded-2xl p-4">

          <div className="flex items-center gap-2 text-slate-500 dark:text-zinc-400">

            <FileText size={16} />

            <p className="text-sm">
              Export Type
            </p>

          </div>

          <h3 className="font-semibold mt-3 dark:text-white">
            {report.type}
          </h3>

        </div>

        <div className="bg-slate-50 dark:bg-zinc-800/70 rounded-2xl p-4">

          <div className="flex items-center gap-2 text-slate-500 dark:text-zinc-400">

            <User2 size={16} />

            <p className="text-sm">
              Generated By
            </p>

          </div>

          <h3 className="font-semibold mt-3 dark:text-white truncate">
            {report.generatedBy}
          </h3>

        </div>

        <div className="bg-slate-50 dark:bg-zinc-800/70 rounded-2xl p-4">

          <div className="flex items-center gap-2 text-slate-500 dark:text-zinc-400">

            <CalendarDays size={16} />

            <p className="text-sm">
              Date
            </p>

          </div>

          <h3 className="font-semibold mt-3 dark:text-white">
            {report.date}
          </h3>

        </div>

      </div>

      <div className="flex items-center gap-3 mt-8">

        <button
          onClick={() =>
            handleViewReport(report)
          }
          className="flex-1 flex items-center justify-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white py-3.5 rounded-2xl font-semibold transition shadow-lg shadow-emerald-500/20"
        >

          <Eye size={18} />

          View Report

        </button>

        <button
          onClick={() =>
            handleDownload(report)
          }
          className="w-14 h-14 rounded-2xl border border-slate-200 dark:border-zinc-700 dark:text-white hover:bg-slate-100 dark:hover:bg-zinc-800 flex items-center justify-center transition"
        >

          <Download size={20} />

        </button>

      </div>

    </div>
  );
}

export default ReportCard;
